---
# tasks file for osx-zsh
- shell: dscl . read ~ UserShell | awk '{print $2}'
  sudo: no
  register: zsh_current_login_shell

- lineinfile: dest=/etc/shells line=/usr/local/bin/zsh state=present owner=root group=wheel mode=0644
  sudo: yes
  when: zsh_current_login_shell.stdout != "/usr/local/bin/zsh"

- shell: id -un
  sudo: no
  register: zsh_login_id
  when: zsh_current_login_shell.stdout != "/usr/local/bin/zsh"

- shell: chsh -s /usr/local/bin/zsh "{{ zsh_login_id.stdout }}"
  sudo: no
  when: zsh_current_login_shell.stdout != "/usr/local/bin/zsh"
