---
# tasks file for hnakamur.zsh-zprezto
- git: repo="{{ zsh_zprezto_git_url }}" dest="{{ zsh_zprezto_work_dir }}"

- copy: src="{{ zsh_zprezto_work_dir }}/runcoms/{{ item }}" dest="~/.{{ item }}"
  with_items: zsh_zprezto_copy_files
